apiVersion: v1
description: Db2 Community Edition
home: 
icon: 
keywords: ['db2u', 'aese', 'oltp', 'ce', 'mpp', 'dashdb', 'db2warehouse', 'warehouse', 'local', 'db2', 'database', 'sql', 'Commercial', 'RHOCP', 'amd64']
maintainers:
- name: IBM Data and AI
name: ibm-db2u
sources:
- https://github.com/IBM/charts/tree/master/stable
tillerVersion: '>=2.9.0'
version: 2.0.0
kubeVersion: ">=1.10.1"
appVersion: 11.5.1.0
